apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
  namespace: <Desired_Namespace>
type: Opaque
data:
  postgress_db_user_name_sonar: ZXJnU29uYVzZXI= #echo -n "db_user_name" | base64
  postgress_db_password_sonar: ZXJnYXJEQlBhc3M=  #echo -n "db_password" | base64
  postgres_db_url_sonar: c29uYXJxdWJlLWF1cm9yYS1jbHVzdGVyLmNsdXN0ZXItY2xlcXd1YXVreDZoLnVzLWVhc3QtMS5ym9uYXdzLmNvbTo1NDMy  #echo -n 'sonarqube-aurora-cluster.cluster-cl.us-east-1.rds.amazonaws.com:5432' | base64
